### ISSUE TITLE
Fix templates

### ISSUE THREAD

**Issue by ram02z** [ram02z/void-templates#1]
- [x] lua-language-server
- [x] rofi-wayland

**Comment by gbrlsnchs** [comment]
Not sure if you're interested, but I have a working template at https://codeberg.org/gbrlsnchs/void-pkgs/src/branch/trunk/srcpkgs/lua-language-server.

As a side note, I based that repo off yours here, so thanks for having this open sourced! :-)

**Comment by ram02z** [comment]
> Not sure if you're interested, but I have a working template at https://codeberg.org/gbrlsnchs/void-pkgs/src/branch/trunk/srcpkgs/lua-language-server.

Thanks! I have been putting off trying to make a template for it due to the large number of git dependencies.

> As a side note, I based that repo off yours here, so thanks for having this open sourced! :-)

No problem and thanks again for the lua-ls template.
